---
version: 2
updates:

  # Maintain npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "bot"
    commit-message:
      prefix: "[CHORE](deps)"
      include: "scope"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
    cooldown:
      default-days: 7

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "bot"
    commit-message:
      prefix: "[CHORE](deps)"
      include: "scope"
    cooldown:
      default-days: 7
