/**
 * Sidebar for the versioned `schema` docs instance (schema/ and
 * schema_versioned_docs/). Snapshotted per version by docs:version:schema.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  schema: [
    { type: 'link', label: '← All docs', href: '/' },
    'index', // Ensure the overview is first
    { type: 'autogenerated', dirName: 'reference' },
  ],
};
module.exports = sidebars;
