/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'getting-data/index'
      },
      collapsed: true,
      items: [
        'getting-data/duckdb',
        'getting-data/overturemaps-py',
        'getting-data/athena-aws',
        'getting-data/synapse-azure',
        {
          type: 'category',
          label: 'Data Mirrors',
          collapsed: true,
          items: [
            'getting-data/data-mirrors/bigquery',
            'getting-data/data-mirrors/databricks',
            'getting-data/data-mirrors/fused',
            'getting-data/data-mirrors/snowflake',
            'getting-data/data-mirrors/wherobots',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      link: {
        type: 'doc',
        id: 'examples/index',
      },
      collapsed: true,
      items: [
        'examples/CARTO',
        'examples/fused',
        'examples/kepler-gl',
        'examples/lonboard',
        'examples/build-a-map',
        'examples/pandas',
        'examples/overture-tiles',
        'examples/QGIS',
        'examples/rapid',
        'examples/spark',
        'examples/wherobots',
      ],
    },
    {
      type: 'category',
      label: 'Data Guides',
      link: {
        type: 'doc',
        id: 'guides/index',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Addresses',
          collapsed: true,
          items: [
            'guides/addresses/overview',
          ],
        },
        {
          type: 'category',
          label: 'Base',
          collapsed: true,
          items: [
            'guides/base/overview',
          ],
        },
        {
          type: 'category',
          label: 'Buildings',
          collapsed: true,
          items: [
            'guides/buildings/overview',
          ],
        },
        {
          type: 'category',
          label: 'Divisions',
          collapsed: true,
          items: [
            'guides/divisions/overview',
          ],
        },
        {
          type: 'category',
          label: 'Places',
          collapsed: true,
          items: [
            'guides/places/overview',
            'guides/places/taxonomy',
          ],
        },
        {
          type: 'category',
          label: 'Transportation',
          collapsed: true,
          items: [
            'guides/transportation/overview',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Global Entity Reference System',
      collapsed: true,
      items: [
        'gers/index',
        'gers/stability',
        'gers/bridge-files',
        'gers/changelog',
        'gers/registry',
        'gers/gers-tutorial',
        'gers/gers-demonstrations',
      ],
    },
    'attribution',
    'release-calendar',
    {
      type: 'category',
      label: 'Schema Reference',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'schema/reference' }],
    },
  ],
};
module.exports = sidebars;
