/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: true,
      items: [
        'getting-data/quick-start',
        'getting-data/cloud-sources',
        'getting-data/explore',
        'getting-data/overturemaps-py',
        'getting-data/duckdb',
        {
          type: 'category',
          label: 'Data Mirrors',
          collapsed: true,
          items: [
            { type: 'autogenerated', dirName: 'getting-data/data-mirrors' },
          ],
        },
      ],
    },
    {
      // Schema reference is a separate, versioned docs instance; see sidebars-schema.js
      type: 'link',
      label: 'Schema Reference',
      href: '/schema/',
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'examples' },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/index',
        {
          type: 'category',
          label: 'Addresses',
          collapsed: true,
          items: [
            'guides/addresses/index',
          ],
        },
        {
          type: 'category',
          label: 'Base',
          collapsed: true,
          items: [
            'guides/base/index',
            'guides/base/bathymetry',
            'guides/base/infrastructure',
          ],
        },
        {
          type: 'category',
          label: 'Buildings',
          collapsed: true,
          items: [
            'guides/buildings/index',
          ],
        },
        {
          type: 'category',
          label: 'Divisions',
          collapsed: true,
          items: [
            'guides/divisions/index',
          ],
        },
        {
          type: 'category',
          label: 'Places',
          collapsed: true,
          items: [
            'guides/places/index',
            'guides/places/taxonomy',
            'guides/places/taxonomy-explorer',
          ],
        },
        {
          type: 'category',
          label: 'Transportation',
          collapsed: true,
          items: [
            'guides/transportation/index',
            'guides/transportation/segments-and-connectors',
            'guides/transportation/scoping-and-travel-modes',
            'guides/transportation/linear-referencing',
            'guides/transportation/roads',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Global Entity Reference System',
      collapsed: true,
      items: [
        'gers/index',
        'gers/stability',
        'gers/bridge-files',
        'gers/changelog',
        'gers/registry',
        'gers/onboarding-services',
        'gers/gers-tutorial',
      ],
    },
    'attribution',
    'release-calendar',
    'support',

  ],
};
module.exports = sidebars;
