// Test fixtures extracted from real schema reference files.
// Names reflect text content AFTER MDX processing (backticks stripped,
// emphasis markers absorbed into adjacent elements).

// From docs/schema/reference/transportation/segment.md Fields table.
// Exercises: simple fields, array fields, annotated fields, deep nesting,
// dot notation, array-then-dot, mixed depth, duplicate base names with
// different annotations.
export const SEGMENT_FIELDS = [
  ['id', 'Id', 'A feature ID.'],
  ['bbox', 'bbox (optional)', 'An optional bounding box for the feature'],
  ['geometry', 'geometry', 'Segment centerline'],
  ['theme', '"transportation"', ''],
  ['type', '"segment"', ''],
  ['version', 'FeatureVersion', ''],
  ['sources[]', 'Sources (list, optional)', 'Information about the source data used to assemble the feature.'],
  ['sources[].property', 'JsonPointer', 'A JSON Pointer identifying the property (field).'],
  ['sources[].dataset', 'string', 'Name of the dataset where the source data can be found.'],
  ['sources[].license', 'StrippedString (optional)', 'Source data license name.'],
  ['sources[].record_id', 'string (optional)', 'Identifies the specific record within the source dataset.'],
  ['sources[].update_time', 'datetime (optional)', 'Last update time of the source data record.'],
  ['sources[].confidence', 'ConfidenceScore (optional)', 'Confidence value from the source dataset.'],
  ['sources[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['subtype', 'Subtype', 'Broad category of transportation segment.'],
  ['access_restrictions[]', 'AccessRules (list, optional)', 'Rules governing access to this road segment'],
  ['access_restrictions[].access_type', 'AccessType', ''],
  ['access_restrictions[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['access_restrictions[].when', 'AccessRestrictionRule.When (optional)', 'Scopes for AccessRestrictionRule.'],
  ['access_restrictions[].when.heading', 'Heading (optional)', 'The heading that the rule applies to.'],
  ['access_restrictions[].when.during', 'OpeningHours (optional)', 'The recurring time span.'],
  ['access_restrictions[].when.mode', 'list<TravelMode> (optional)', 'A list of one or more travel modes.'],
  ['access_restrictions[].when.using', 'list<PurposeOfUse> (optional)', 'A list of one or more usage purposes.'],
  ['access_restrictions[].when.recognized', 'list<RecognizedStatus> (optional)', 'A list of one or more recognized status values.'],
  ['access_restrictions[].when.vehicle', 'VehicleAxleCountSelector | ... (list, optional)', 'A list of one or more vehicle parameters.'],
  ['connectors[]', 'list<ConnectorReference> (optional)', 'List of connectors.'],
  ['connectors[].connector_id', 'Id', 'A unique identifier'],
  ['connectors[].at', 'LinearlyReferencedPosition (optional)', 'The linearly-referenced position.'],
  ['level_rules[]', 'LevelRules (list, optional)', 'Defines the Z-order of the road segment.'],
  ['level_rules[].value', 'Level', 'Z-order of the feature where 0 is visual level'],
  ['level_rules[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['routes[]', 'Routes (list, optional)', 'Routes this segment belongs to'],
  ['routes[].name', 'StrippedString (optional)', 'Full name of the route'],
  ['routes[].network', 'StrippedString (optional)', 'Name of the highway system'],
  ['routes[].ref', 'StrippedString (optional)', 'Code or number used to reference the route'],
  ['routes[].symbol', 'StrippedString (optional)', 'URL or description of route signage'],
  ['routes[].wikidata', 'WikidataId (optional)', 'A wikidata ID'],
  ['routes[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['subclass_rules[]', 'SubclassRules (list, optional)', 'Set of subclasses scoped along segment'],
  ['subclass_rules[].value', 'Subclass', ''],
  ['subclass_rules[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['names', 'Names (optional)', ''],
  ['names.primary', 'StrippedString', 'The most commonly used name.'],
  ['names.common', 'CommonNames (map, optional)', ''],
  ['names.rules[]', 'list<NameRule> (optional)', 'Rules for names.'],
  ['names.rules[].value', 'StrippedString', 'The actual name value.'],
  ['names.rules[].variant', 'NameVariant', 'The name variant for this name rule.'],
  ['names.rules[].language', 'LanguageTag (optional)', 'The language in which the name value is specified.'],
  ['names.rules[].perspectives', 'Perspectives (optional)', 'Political perspectives.'],
  ['names.rules[].perspectives.mode', 'PerspectiveMode', 'Whether the perspective holder accepts or disputes this name.'],
  ['names.rules[].perspectives.countries', 'CountryCodeAlpha2 (list)', 'Countries holding the given mode of perspective.'],
  ['names.rules[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['names.rules[].side', 'Side (optional)', 'The side that the rule applies to.'],
  ['class (Road)', 'RoadClass', ''],
  ['destinations[] (Road)', 'Destinations (list, optional)', 'Describes objects that can be reached by following a transportation segment.'],
  ['destinations[].from_connector_id', 'Id', 'Identifies the point of physical connection.'],
  ['destinations[].to_connector_id', 'Id', 'Identifies the point of physical connection.'],
  ['destinations[].to_segment_id', 'Id', 'Identifies the segment to transition to.'],
  ['destinations[].final_heading', 'Heading', 'Direction of travel on the segment.'],
  ['destinations[].labels[]', 'list<DestinationLabels> (optional)', 'Labeled destinations.'],
  ['destinations[].labels[].value', 'StrippedString', 'Names the object that is reached'],
  ['destinations[].labels[].type', 'DestinationLabelType', ''],
  ['destinations[].symbols', 'list<DestinationSignSymbol> (optional)', 'Symbols or icons on the sign.'],
  ['destinations[].when', 'DestinationRule.When (optional)', 'Scope for DestinationRule.'],
  ['destinations[].when.heading', 'Heading', 'The heading that the rule applies to.'],
  ['prohibited_transitions[] (Road)', 'ProhibitedTransitions (list, optional)', 'Rules preventing transitions.'],
  ['prohibited_transitions[].sequence[]', 'list<SequenceEntry>', 'Ordered sequence of connector/segment pairs.'],
  ['prohibited_transitions[].sequence[].connector_id', 'Id', 'Identifies the point of physical connection.'],
  ['prohibited_transitions[].sequence[].segment_id', 'Id', 'Identifies the segment.'],
  ['prohibited_transitions[].final_heading', 'Heading', 'Direction of travel that is prohibited.'],
  ['prohibited_transitions[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['prohibited_transitions[].when', 'ProhibitedTransitionRule.When (optional)', 'Scopes for ProhibitedTransitionRule.'],
  ['prohibited_transitions[].when.heading', 'Heading (optional)', 'The heading that the rule applies to.'],
  ['prohibited_transitions[].when.during', 'OpeningHours (optional)', 'The recurring time span.'],
  ['prohibited_transitions[].when.mode', 'list<TravelMode> (optional)', 'A list of one or more travel modes.'],
  ['prohibited_transitions[].when.using', 'list<PurposeOfUse> (optional)', 'A list of one or more usage purposes.'],
  ['prohibited_transitions[].when.recognized', 'list<RecognizedStatus> (optional)', 'A list of one or more recognized status values.'],
  ['prohibited_transitions[].when.vehicle', 'VehicleAxleCountSelector | ... (list, optional)', 'A list of one or more vehicle parameters.'],
  ['road_flags[] (Road)', 'RoadFlags (list, optional)', 'Set of boolean attributes applicable to roads.'],
  ['road_flags[].values', 'list<RoadFlag>', ''],
  ['road_flags[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['road_surface[] (Road)', 'Surfaces (list, optional)', 'Physical surface of the road.'],
  ['road_surface[].value', 'RoadSurface', ''],
  ['road_surface[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['speed_limits[] (Road)', 'SpeedLimits (list, optional)', 'Rules governing speed on this road segment'],
  ['speed_limits[].max_speed', 'Speed (optional)', ''],
  ['speed_limits[].max_speed.value', 'SpeedValue', 'Speed value'],
  ['speed_limits[].max_speed.unit', 'SpeedUnit', ''],
  ['speed_limits[].min_speed', 'Speed (optional)', ''],
  ['speed_limits[].min_speed.value', 'SpeedValue', 'Speed value'],
  ['speed_limits[].min_speed.unit', 'SpeedUnit', ''],
  ['speed_limits[].is_max_speed_variable', 'boolean (optional)', 'Indicates a variable speed corridor'],
  ['speed_limits[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['speed_limits[].when', 'SpeedLimitRule.When (optional)', 'Scopes for SpeedLimitRule.'],
  ['speed_limits[].when.heading', 'Heading (optional)', 'The heading that the rule applies to.'],
  ['speed_limits[].when.during', 'OpeningHours (optional)', 'The recurring time span.'],
  ['speed_limits[].when.mode', 'list<TravelMode> (optional)', 'A list of one or more travel modes.'],
  ['speed_limits[].when.using', 'list<PurposeOfUse> (optional)', 'A list of one or more usage purposes.'],
  ['speed_limits[].when.recognized', 'list<RecognizedStatus> (optional)', 'A list of one or more recognized status values.'],
  ['speed_limits[].when.vehicle', 'VehicleAxleCountSelector | ... (list, optional)', 'A list of one or more vehicle parameters.'],
  ['subclass (Road)', 'Subclass (optional)', ''],
  ['width_rules[] (Road)', 'WidthRules (list, optional)', 'Edge-to-edge width of the road.'],
  ['width_rules[].value', 'Width', ''],
  ['width_rules[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['class (Rail)', 'RailClass', ''],
  ['rail_flags[] (Rail)', 'RailFlags (list, optional)', 'Set of boolean attributes applicable to railways.'],
  ['rail_flags[].values', 'list<RailFlag>', ''],
  ['rail_flags[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
];

// From docs/schema/reference/base/division.md
// Exercises: pure-dot parent with multiple children, no arrays.
export const CARTOGRAPHY_FIELDS = [
  ['cartography', 'CartographicHints (optional)', ''],
  ['cartography.prominence', 'Prominence (optional)', 'Subjective scale of feature significance.'],
  ['cartography.min_zoom', 'MinZoom (optional)', 'Recommended minimum tile zoom level.'],
  ['cartography.max_zoom', 'MaxZoom (optional)', 'Recommended maximum tile zoom level.'],
  ['cartography.sort_key', 'SortKey (optional)', 'Integer indicating the recommended draw order.'],
];

// From docs/schema/reference/places/place.md
// Exercises: deep pure-dot-notation chain (brand -> brand.names -> ...),
// 5-segment paths where first two segments are plain dot notation.
export const BRAND_FIELDS = [
  ['brand', 'Brand (optional)', 'The brand associated with the place.'],
  ['brand.names', 'Names (optional)', ''],
  ['brand.names.primary', 'StrippedString', 'The most commonly used name.'],
  ['brand.names.common', 'CommonNames (map, optional)', ''],
  ['brand.names.rules[]', 'list<NameRule> (optional)', 'Rules for names.'],
  ['brand.names.rules[].value', 'StrippedString', 'The actual name value.'],
  ['brand.names.rules[].variant', 'NameVariant', 'The name variant for this name rule.'],
  ['brand.names.rules[].language', 'LanguageTag (optional)', 'The language.'],
  ['brand.names.rules[].perspectives', 'Perspectives (optional)', 'Political perspectives.'],
  ['brand.names.rules[].perspectives.mode', 'PerspectiveMode', 'Whether the perspective holder accepts or disputes.'],
  ['brand.names.rules[].perspectives.countries', 'CountryCodeAlpha2 (list)', 'Countries holding the perspective.'],
  ['brand.names.rules[].between', 'LinearlyReferencedRange (list, optional)', 'The linearly-referenced sub-segment.'],
  ['brand.names.rules[].side', 'Side (optional)', 'The side that the rule applies to.'],
  ['brand.wikidata', 'WikidataId (optional)', 'A wikidata ID'],
];
