---
name: Staging Deploy
run-name: Publish docs to staging website

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  DOCS_PATH: docs
  PREVIEW_PATH: /${{ github.event.repository.name }}/pr/${{ github.event.number }}
  STAGING_URL: https://staging.overturemaps.org
  SCHEMA_PREVIEW: false # Set to true to only publish Schema reference docs
  AWS_ROLE_ARN: arn:aws:iam::763944545891:role/pages-staging-oidc-overturemaps
  AWS_REGION: us-west-2
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main docs repo repository and build.
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: 'package.json'

      - uses: lowlydba/sustainable-npm@v2

      - run: npm ci --omit=dev

      - name: Generate schema markdown docs
        uses: OvertureMaps/workflows/.github/actions/generate-schema-docs@main
        with:
          output-dir: ${{ github.workspace }}/docs/schema/reference

      - name: Build Docusaurus website
        run: npm run build
        env:
          DOCUSAURUS_URL: ${{ env.STAGING_URL }}/
          DOCUSAURUS_BASE_URL: ${{ env.PREVIEW_PATH }}/
          SCHEMA_PREVIEW: ${{ env.SCHEMA_PREVIEW }}

      - name: Upload docs build as an artifact 📦
        uses: actions/upload-artifact@v7
        with:
          path: build
          name: build-artifact

  deploy:
    name: Deploy
    runs-on: ubuntu-slim
    needs: build
    environment:
      name: staging
      url: ${{ env.STAGING_URL }}${{ env.PREVIEW_PATH }}/index.html

    steps:
      - name: Configure AWS credentials 🔐
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download artifacts 📥
        uses: actions/download-artifact@v8
        with:
          name: build-artifact
          path: build

      - name: Copy to S3
        run: |
          aws s3 sync --delete --quiet build s3://overture-managed-staging-usw2/gh-pages${{ env.PREVIEW_PATH }}/

      - name: Bust the Cache
        run: aws cloudfront create-invalidation --distribution-id E1KP2IN0H2RGGT --paths "${{ env.PREVIEW_PATH }}/*"

      - name: Get deploy timestamp
        id: timestamp
        run: |
          echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "short_sha=$(echo '${{ github.event.pull_request.head.sha }}' | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987 # v3.0.2
        with:
          message: |
            ## 🗺️ OMF Docs preview is live!

            | | |
            |-------------|----------------------------------------------------------|
            | **Preview** | ${{ env.STAGING_URL }}${{ env.PREVIEW_PATH }}/index.html |
            | **Updated** | ${{ steps.timestamp.outputs.time }} |
            | **Commit**  | [${{ steps.timestamp.outputs.short_sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}) |

            > [!NOTE]
            > This preview updates automatically with each push to this PR.
