---
name: Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json

      - name: Configure sustainable npm
        uses: lowlydba/sustainable-npm@31d51025884f424f58f22e4e6578178bb4e79632 # v3.0.0

      - name: Install NPM dependencies
        run: npm ci

      - name: Run tests
        run: npm test
